import { USE_MOCKS, apiFetch, delay } from "./client";
import type { CompanyDiagnostic } from "./types";

/**
 * GET /api/company/diagnostic — admin only. Latest weekly company-mood
 * snapshot generated by the n8n flow. The audit workspace shows it as a
 * pre-screen for Dirección General users only.
 */
export async function getDiagnostic(): Promise<CompanyDiagnostic> {
  if (USE_MOCKS) {
    await delay(180);
    return {
      has_data: true,
      mood_label: "Tensión productiva",
      mood_score: 6.5,
      summary:
        "## Lectura ejecutiva\n\nLa empresa muestra un ánimo **estable con tensión productiva**. La fricción promedio se mantiene en rango medio y se convirtió en valor: varias extracciones de Oro y Joya esta semana.\n\n### Riesgo\n\nUn foco de calcificación puntual en un equipo; vigilar que no se sostenga.",
      payload: {
        mood_label: "Tensión productiva",
        mood_score: 6.5,
        tensiones: ["Calcificación puntual en un equipo"],
        focos_de_atencion: ["Revisar acompañamiento del equipo con acoplamiento"],
        senales_positivas: ["Extracción sostenida de Oro/Joya", "Encauzamientos al alza"],
      },
      period_start: new Date(Date.now() - 7 * 864e5).toISOString(),
      period_end: new Date().toISOString(),
      generated_at: new Date().toISOString(),
    };
  }
  return apiFetch<CompanyDiagnostic>("/api/company/diagnostic");
}
