/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppOracleRouteImport } from './routes/_app.oracle'
import { Route as AppKnowledgeRouteImport } from './routes/_app.knowledge'
import { Route as AppHiveRouteImport } from './routes/_app.hive'
import { Route as AppAuditRouteImport } from './routes/_app.audit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOracleRoute = AppOracleRouteImport.update({
  id: '/oracle',
  path: '/oracle',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppHiveRoute = AppHiveRouteImport.update({
  id: '/hive',
  path: '/hive',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AppAuditRoute
  '/hive': typeof AppHiveRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/oracle': typeof AppOracleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AppAuditRoute
  '/hive': typeof AppHiveRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/oracle': typeof AppOracleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/hive': typeof AppHiveRoute
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/oracle': typeof AppOracleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/audit' | '/hive' | '/knowledge' | '/oracle'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/audit' | '/hive' | '/knowledge' | '/oracle'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/audit'
    | '/_app/hive'
    | '/_app/knowledge'
    | '/_app/oracle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/oracle': {
      id: '/_app/oracle'
      path: '/oracle'
      fullPath: '/oracle'
      preLoaderRoute: typeof AppOracleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hive': {
      id: '/_app/hive'
      path: '/hive'
      fullPath: '/hive'
      preLoaderRoute: typeof AppHiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppHiveRoute: typeof AppHiveRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppOracleRoute: typeof AppOracleRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppHiveRoute: AppHiveRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppOracleRoute: AppOracleRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
