/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProposalsRouteImport } from './routes/_app.proposals'
import { Route as AppOracleRouteImport } from './routes/_app.oracle'
import { Route as AppKnowledgeRouteImport } from './routes/_app.knowledge'
import { Route as AppHiveRouteImport } from './routes/_app.hive'
import { Route as AppAuditRouteImport } from './routes/_app.audit'

const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProposalsRoute = AppProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => AppRoute,
} as any)
const AppOracleRoute = AppOracleRouteImport.update({
  id: '/oracle',
  path: '/oracle',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppHiveRoute = AppHiveRouteImport.update({
  id: '/hive',
  path: '/hive',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/audit': typeof AppAuditRoute
  '/hive': typeof AppHiveRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/oracle': typeof AppOracleRoute
  '/proposals': typeof AppProposalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/audit': typeof AppAuditRoute
  '/hive': typeof AppHiveRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/oracle': typeof AppOracleRoute
  '/proposals': typeof AppProposalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/hive': typeof AppHiveRoute
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/oracle': typeof AppOracleRoute
  '/_app/proposals': typeof AppProposalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/set-password'
    | '/audit'
    | '/hive'
    | '/knowledge'
    | '/oracle'
    | '/proposals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/set-password'
    | '/audit'
    | '/hive'
    | '/knowledge'
    | '/oracle'
    | '/proposals'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/set-password'
    | '/_app/audit'
    | '/_app/hive'
    | '/_app/knowledge'
    | '/_app/oracle'
    | '/_app/proposals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetPasswordRoute: typeof SetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/proposals': {
      id: '/_app/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof AppProposalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oracle': {
      id: '/_app/oracle'
      path: '/oracle'
      fullPath: '/oracle'
      preLoaderRoute: typeof AppOracleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hive': {
      id: '/_app/hive'
      path: '/hive'
      fullPath: '/hive'
      preLoaderRoute: typeof AppHiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppHiveRoute: typeof AppHiveRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppOracleRoute: typeof AppOracleRoute
  AppProposalsRoute: typeof AppProposalsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppHiveRoute: AppHiveRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppOracleRoute: AppOracleRoute,
  AppProposalsRoute: AppProposalsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetPasswordRoute: SetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
